### ISSUE TITLE
set up to combine for more than TWO algorithms in composite algorithms

### ISSUE THREAD

**Issue by clobart** [ARS-toscana/ApplyComponentStrategy#7]
Now we have composite algorithms ONLY with TWO algorithms at time, we want to improve it, usign algorithm NOT definying before. the graph will be the same as now.

i.e. (1,2,3) OR (4,5,6): we have only one intersection btw the TWO groups

**Comment by RosaMGini** [comment]
add 

#' @param composites_to_be_compared(list of integers, default=NULL). Each list is associated to a composite algorithm, the integers refer to the components, therefore the integers must be <= the number of components
#' @param labels_of_composites_to_be_compared(list of str, optional, default=components). This list must have the same length as -composites_to_be_compared-; each string is the label of the corresponding composite.

#' @param composites (list of pairs of integers, default=NULL). Each pair is associated to a pair of algorithms to be compared; it contains the numbering of the two algorithms that form the component; the numbering refers to the order in the list -c(components, composites_to_be_compared)
#' @param labels_of_components (list of str, optional, default=components). This list must have the same length as -components-; each string is the label of the corresponding component.

input=read.csv(input)
output <- ApplyComponentStrategy(dataset=input,
                                                            components= c(“alg1”, “alg2”, “alg3”, “alg4”),
                                                            composites_to_be_compared = list(
                                                                                                                     list(1,2),
                                                                                                                     list(3,4),
                                                                                                                     list(2,4),
                                                                                                                     list(2,4),
                                                                                                                     list(1,2,3,4),
                                                                                                                     )
                                                            composites=list(
                                                                                                                     list(1,3),
                                                                                                                     list(2,4),              
                                                                                                                     list(5,6), # 5 and 6 refer to the 5th and 6th of the list c(components, composites_to_be_compared)

labels_of_components=c(
“Narrow, meaning H",
“Possible, meaning H",
“Narrow, meaning P",
“Possible, meaning P"
)
labels_of_composites_to_be_compared=c(
“All meaning H",
“All meanings P",
“All narrow",
“All possible"
)
llabels_of_composites_to_be_compared=c(
“Compare narrow H vs P",
“Compare possible H vs P",
“Compare narrow vs possible"
)
count_var=’persons’,
expected_numer=N_TRUE,
K=1000

**Comment by GiorgioLimoncella** [comment]
Resolved in branch [**composites_to_be_compared**](https://github.com/ARS-toscana/ApplyComponentStrategy/tree/composites_to_be_compared)
